version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chesso-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: chesso-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]
    
  nginx:
      build: 
        context: ./nginx
      container_name: nginx
      ports:
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../react-build:/usr/share/nginx/html
        - ./nginx/certs:/etc/nginx/certs
      entrypoint: ["/bin/sh", "/etc/nginx/certs/entrypoint.sh"]
      depends_on:
        - api 
volumes:
  postgres_data:

