version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chesso-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: chesso
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: chesso-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres 
      DB_NAME: chesso
      JWT_SECRET: secret777
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]
    
  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./react-build:/usr/share/nginx/html
      depends_on:
        - api 
volumes:
  postgres_data:

