version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chesso-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: chesso-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]
    
  nginx:
      build: 
        context: ./nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../react-build:/usr/share/nginx/html/app
        - ./landing:/usr/share/nginx/html/landing
        - ./certbot/certs:/etc/letsencrypt
        - ./nginx/html:/var/www/certbot
      depends_on:
        - api 
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot
        --webroot-path=/var/www/certbot
        --email aleksadoderovic@gmail.com
        --agree-tos
        --no-eff-email
        -d chesso.org -d www.chesso.org"
volumes:
  postgres_data:

